<?php

namespace App\Filament\Clusters\Products\Resources;

use App\Filament\Clusters\Products;
use App\Models\ShopCategory;
use Filament\Forms;
use Filament\Forms\Components\SpatieMediaLibraryFileUpload;
use Filament\Forms\Form;
use Filament\Notifications\Notification;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Support\Str;

class CategoryResource extends Resource
{
    protected static ?string $model = ShopCategory::class;

    protected static ?string $cluster = Products::class;

    protected static ?string $recordTitleAttribute = 'name';

    protected static ?string $navigationIcon = 'heroicon-o-tag';

    public static function getNavigationParentItem(): ?string
    {
        return __('main.Products'); // TODO: Change the autogenerated stub
    }

    public static function getNavigationLabel(): string
    {
        return __('main.ShopCategory'); // TODO: Change the autogenerated stub
    }
public static function getLabel(): ?string
{
    return __('main.ShopCategory');// TODO: Change the autogenerated stub
}

    protected static ?int $navigationSort = 1;

    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                Forms\Components\Section::make()
                    ->schema([
                        Forms\Components\Grid::make()
                            ->schema([

                                Forms\Components\Tabs::make('Tabs')
                                    ->tabs([
                                        Forms\Components\Tabs\Tab::make('O\'zbek')
                                            ->schema([
                                                Forms\Components\TextInput::make('name_uz')
                                                    ->required()
                                                    ->maxLength(255)
                                                    ->live(onBlur: true)
                                                    ->label(__('main.Name'))
                                                    ->afterStateUpdated(fn(string $operation, $state, Forms\Set $set) => $operation === 'create' ? $set('slug_uz', Str::slug($state)) : null),

                                                Forms\Components\TextInput::make('slug_uz')
                                                    ->dehydrated()
                                                    ->label(__('main.Slug'))
                                                    ->required()
                                                    ->maxLength(255)
                                                    ->unique(ShopCategory::class, 'slug_uz', ignoreRecord: true),
                                                Forms\Components\MarkdownEditor::make('description_uz')
                                                    ->label(__('main.Content')),

                                                Forms\Components\TextInput::make('meta_title_uz')
                                                    ->maxLength(255)
                                                    ->live(onBlur: true)
                                                    ->required()
                                                    ->label(__('main.MetaTitle')),

                                                Forms\Components\MarkdownEditor::make('meta_description_uz')
                                                    ->columnSpan('full')
                                                    ->required()
                                                    ->label(__('main.MetaContent')),

                                            ]),

                                        Forms\Components\Tabs\Tab::make('Pусский')
                                            ->schema([
                                                Forms\Components\TextInput::make('name_ru')
                                                    ->required()
                                                    ->maxLength(255)
                                                    ->live(onBlur: true)
                                                    ->label(__('main.Name'))
                                                    ->afterStateUpdated(fn(string $operation, $state, Forms\Set $set) => $operation === 'create' ? $set('slug_ru', Str::slug($state)) : null),

                                                Forms\Components\TextInput::make('slug_ru')
                                                    ->dehydrated()
                                                    ->label(__('main.Slug'))
                                                    ->required()
                                                    ->maxLength(255)
                                                    ->unique(ShopCategory::class, 'slug_ru', ignoreRecord: true),
                                                Forms\Components\MarkdownEditor::make('description_ru')
                                                    ->label(__('main.Content')),
                                                Forms\Components\TextInput::make('meta_title_ru')
                                                    ->maxLength(255)
                                                    ->live(onBlur: true)
                                                    ->required()
                                                    ->label(__('main.MetaTitle')),

                                                Forms\Components\MarkdownEditor::make('meta_description_ru')
                                                    ->columnSpan('full')
                                                    ->required()
                                                    ->label(__('main.MetaContent')),
                                            ]),


                                        Forms\Components\Tabs\Tab::make('English')
                                            ->schema([
                                                Forms\Components\TextInput::make('name_en')
                                                    ->required()
                                                    ->maxLength(255)
                                                    ->live(onBlur: true)
                                                    ->label(__('main.Name'))
                                                    ->afterStateUpdated(fn(string $operation, $state, Forms\Set $set) => $operation === 'create' ? $set('slug_en', Str::slug($state)) : null),

                                                Forms\Components\TextInput::make('slug_en')
                                                    ->dehydrated()
                                                    ->label(__('main.Slug'))
                                                    ->required()
                                                    ->maxLength(255)
                                                    ->unique(ShopCategory::class, 'slug_en', ignoreRecord: true),

                                                Forms\Components\MarkdownEditor::make('description_en')
                                                    ->label(__('main.Content')),
                                                Forms\Components\TextInput::make('meta_title_en')
                                                    ->maxLength(255)
                                                    ->live(onBlur: true)
                                                    ->required()
                                                    ->label(__('main.MetaTitle')),

                                                Forms\Components\MarkdownEditor::make('meta_description_en')
                                                    ->columnSpan('full')
                                                    ->required()
                                                    ->label(__('main.MetaContent')),
                                            ]),
                                    ])
                                    ->columnSpan('full'),
                            ]),
                        Forms\Components\Toggle::make('is_visible')
                            ->label(__('main.Visible'))
                            ->default(true),

                        Forms\Components\Select::make('parent_id')
                            ->label(__('main.Parent'))
                            ->relationship('parent', 'name_uz', fn(Builder $query) => $query->where('parent_id', null))
                            ->searchable()
                            ->placeholder('Select parent category'),
                        Forms\Components\Section::make(__('main.Image'))
                            ->schema([
                                SpatieMediaLibraryFileUpload::make('media')
                                    ->collection('category-image')
                                    ->hiddenLabel()
                                    ->imageEditor('media'),
                            ])
                            ->collapsible(),
                    ]),
            ])
            ->columns(3);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                Tables\Columns\TextColumn::make('name_' . app()->getLocale())
                    ->label(__('main.Name'))
                    ->searchable()
                    ->sortable(),
                Tables\Columns\SpatieMediaLibraryImageColumn::make('category-image')
                    ->label(__('main.Image'))
                    ->collection('category-image'),
                Tables\Columns\TextColumn::make('parent.name_' . app()->getLocale())
                    ->label(__('main.Parent'))
                    ->searchable()
                    ->sortable(),
                Tables\Columns\IconColumn::make('is_visible')
                    ->label(__('main.Visible'))
                    ->sortable(),
            ])
            ->filters([
                //
            ])
            ->actions([
                Tables\Actions\EditAction::make(),
            ])
            ->groupedBulkActions([
                Tables\Actions\DeleteBulkAction::make()
                    ->action(function () {
                        Notification::make()
                            ->title('Now, now, don\'t be cheeky, leave some records for others to play with!')
                            ->warning()
                            ->send();
                    }),
            ]);
    }

    public static function getRelations(): array
    {
        return [
            \App\Filament\Clusters\Products\Resources\CategoryResource\RelationManagers\ProductsRelationManager::class,
        ];
    }

    public static function getPages(): array
    {
        return [
            'index' => \App\Filament\Clusters\Products\Resources\CategoryResource\Pages\ListCategories::route('/'),
            'create' => \App\Filament\Clusters\Products\Resources\CategoryResource\Pages\CreateCategory::route('/create'),
            'edit' => \App\Filament\Clusters\Products\Resources\CategoryResource\Pages\EditCategory::route('/{record}/edit'),
        ];
    }
}
