<?php

namespace App\Filament\Resources;

use App\Filament\Resources\ContactResource\Pages;
use App\Filament\Resources\ContactResource\RelationManagers;
use App\Models\Contact;
use App\Models\Language;
use Filament\Forms;
use Filament\Forms\Form;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\SoftDeletingScope;

class ContactResource extends Resource
{
    protected static ?string $model = Contact::class;
    public static function getNavigationLabel(): string
    {
        return __('main.contact'); // TODO: Change the autogenerated stub
    }
    public static function getNavigationGroup(): ?string
    {
        return __('main.Contact');  // TODO: Change the autogenerated stub
    }
    public static function getLabel(): ?string
    {
        return __('main.contact');  // TODO: Change the autogenerated stub
    }

    protected static ?string $navigationIcon = 'heroicon-o-phone';

    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                Forms\Components\Select::make('language_id')
                    ->label(__('main.Language'))
                    ->options(Language::pluck('name', 'id'))
                    ->extraAttributes(['style' => 'border-radius: 5px; width: 25%'])
                    ->required(),

                Forms\Components\Section::make(__('main.contact'))
                    ->schema([
                        Forms\Components\Grid::make(2)
                            ->schema([

                                Forms\Components\TextInput::make('address')
                                ->label(__('main.Address')),
                                Forms\Components\TextInput::make('work_time')
                                ->label(__('main.WorkTime')),
                            ]),
                        Forms\Components\Grid::make(2)
                            ->schema([
                                Forms\Components\TextInput::make('phone1')
                                    ->label(__('main.Phone'))
                                    ->regex('/^\+998 \(\d{2}\) \d{3}-\d{2}-\d{2}$/')
                                    ->helperText('+998 (99) 999-99-99'),
                                Forms\Components\TextInput::make('phone2')
                                    ->label(__('main.Phone'))
                                    ->regex('/^\+998 \(\d{2}\) \d{3}-\d{2}-\d{2}$/')
                                    ->helperText('+998 (99) 999-99-99'),
                            ]),
                        Forms\Components\Grid::make(2)
                            ->schema([
                                Forms\Components\TextInput::make('email1')
                                    ->label(__('main.Email'))
                                    ->email(),
                                Forms\Components\TextInput::make('email2')
                                    ->label(__('main.Email'))
                                    ->email(),
                            ]),
                        Forms\Components\Section::make('Social media')
                            ->schema([
                                Forms\Components\Grid::make(2)
                                    ->schema([
                                        Forms\Components\TextInput::make('facebook')
                                            ->label('Facebook')
                                            ->placeholder('Facebook'),
                                        Forms\Components\TextInput::make('telegram')
                                            ->label('Telegram')
                                            ->placeholder('Telegram'),
                                        Forms\Components\TextInput::make('instagram')
                                            ->label('Instagram')
                                            ->placeholder('Instagram'),
                                        Forms\Components\TextInput::make('youtube')
                                            ->label('Youtube')
                                            ->placeholder('Youtube'),
                                        Forms\Components\TextInput::make('linkedin')
                                            ->label('LinkedIn')
                                            ->placeholder('LinkedIn'),
                                    ]),

                            ]),
                        Forms\Components\Section::make()
                            ->schema([
                                Forms\Components\RichEditor::make('text')
                                ->label(__('main.Content')),
                            ])
                    ])
            ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                Tables\Columns\TextColumn::make('language.name')->label(__('main.Language')),
                Tables\Columns\TextColumn::make('address')->label(__('main.Address')),
                Tables\Columns\TextColumn::make('work_time')->label(__('main.WorkTime')),
                Tables\Columns\TextColumn::make('phone1')->label(__('main.Phone')),
            ])
            ->filters([
                //
            ])
            ->actions([
                Tables\Actions\EditAction::make(),
            ])
            ->bulkActions([
                Tables\Actions\BulkActionGroup::make([
                    Tables\Actions\DeleteBulkAction::make(),
                ]),
            ]);
    }

    public static function getRelations(): array
    {
        return [
            //
        ];
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ListContacts::route('/'),
            'create' => Pages\CreateContact::route('/create'),
            'edit' => Pages\EditContact::route('/{record}/edit'),
        ];
    }
}
